### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by hydratioNx99** [MJMODZZ/FallGuys-Cheat#1]
when compiling I get the error  "client_game_manager": undeclared identifier

![devenv_ETW6CKnaQg](https://user-images.githubusercontent.com/29978081/180671150-774e68b8-0fbf-4512-8915-013c1b2aa8d2.png)

**Comment by MJMODZZ** [comment]
you have to declare or remove it.

**Comment by hydratioNx99** [comment]
how or where?

**Comment by MJMODZZ** [comment]
> how or where though?

I recomment declaring it. If you dont know how, delete it

**Comment by MJMODZZ** [comment]
We are going to make a completely new fallguys cheat with ImGui and a working driver.

**Comment by hydratioNx99** [comment]
I see
