### ISSUE TITLE
Impossible to inject

### ISSUE THREAD

**Issue by RKT-MetaHook** [MJMODZZ/FallGuys-Cheat#2]
Tryied to inject with 2 private dll's injectors, my own injector, process hacker and xenos and it gives ACCESS DENIED when injecting the dll

**Comment by hydratioNx99** [comment]
do they bypass eac?

**Comment by MJMODZZ** [comment]
> 

you need a EAC bypassing driver and a undetected Injector. I dont provide them here on github
